FROM rust:latest

RUN apt update && apt upgrade -y
RUN apt install -y \
    cmake

RUN rustup update
RUN rustup component add rustfmt

WORKDIR /app

ADD docker/Cargo.toml ./

RUN grep '\[dependencies\]' Cargo.toml \
    && cargo build \
    || echo "Skipping cargo update..."
