FROM rust:latest

RUN apt update && apt upgrade -y
RUN apt install -y \
    cmake

RUN rustup update

WORKDIR /app

COPY Cargo.toml ./

RUN grep '[dependencies]' \
    && cargo update \
    || echo "Skipping cargo update..."

CMD ["cargo", "build"]
