FROM rust:latest

RUN apt update && apt upgrade -y
RUN apt install -y \
    cmake

RUN rustup update

WORKDIR /app

ADD docker/build.tar ./

RUN grep '\[dependencies\]' \
    && cargo build \
    || echo "Skipping cargo update..."

CMD ["cargo", "build"]
